config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  devise_for :users
  root to: "exchange#index" 
  resources :exchange, only: [:index]
  resources :books, except: [:destroy, :edit, :update]
  resources :adverts, except: [:edit, :update]
  resources :orders, only: [:new, :complete]

# For the stripe checkout
get 'order/complete', to: 'orders#complete'
get 'order/cancel', to: 'exchange#index'

# For the destroy methods
delete "adverts/:id", to: "adverts#destroy", as: "advert_destroy_path"

# For about & contact page
get "/about", to: "exchange#about", as: "about"
get "/contact", to: "exchange#contact", as: "contact"

end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :book
  # This defines the relationship between `books` and `adverts` where a book has many adverts and adverts belong to a book.
  belongs_to :seller, class_name: "User"
  # This defines the relationship between 'users' and  'adverts' where a single user can have many advert and an advert can only have one user.
  has_one_attached :cover

  def self.order_by_user
    adverts=[]
    Advert.order(:users).each do |user|
      adverts += user.adverts.order(:book_id)
    end
    return adverts
  end

  def self.order_by_price
    return Advert.order(:price)
  end 

  def self.order_by_created
    return Advert.order(:created_at).reverse_order
  end
  
  def self.create_advert(book_id, price, condition, seller_id)
      advert = Advert.new(book_id: book_id, price: price, condition: condition, seller_id: seller_id)
      advert.save!
    return advert
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :adverts
    validates :title, presence: true

    def self.select_book(title)
        books = GoogleBooks.search(title)
        book = books.first
        if book == nil
            return false
        end
        new_book = Book.new
        new_book.title = book.title
        new_book.isbn = book.isbn
        new_book.authors = book.authors
        new_book.description = book.description
        new_book.image_link = book.image_link
        new_book.save
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :advert
  belongs_to :buyer, class_name: "User"

  def self.create_order(advert_id, buyer_id)
    order = Order.new(advert_id: advert_id, buyer_id: buyer_id)
    order.save!
  return order
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 6..64
  has_many :adverts
  # This defines the relationship between `users` and `adverts` where the user has many adverts and adverts belong to user.
  has_many :orders
  # This defines the relationship between `users` and `orders` where the user has many orders and orders belong to user.
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :authenticate_user! 
  def index
    @adverts = Advert.order_by_created
    @book = Book.all    
  end 
  
  def new
    @advert = Advert.new
    @current_book = Book.find(params[:book_id])
  end
  
  def create
    @advert = Advert.create_advert(params[:advert][:book_id], params[:advert][:price], params[:advert][:condition], params[:advert][:seller_id])
    @advert.cover.attach(params[:advert][:cover])
    redirect_to adverts_path
  end
  
  def show
    @advert = Advert.find(params[:id])
    @seller_id = @advert.seller_id
  end
  
  def destroy
    advert_id = params[:id]
    Advert.destroy(advert_id)
    redirect_to adverts_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :username ])
        devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :username])
      end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.select_book(params[:book][:title])
    if @book == false
      flash[:info] = "Could not find that book."
    end
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/exchange_controller.rb
class ExchangeController < ApplicationController
  
  def index
  end

  def about
  end

  def contact
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    
    def new
        @order = Order.new
        @advert = Advert.find(params[:advert_id])
       
        Stripe.api_key = Rails.application.credentials.dig(:stripe, :api_secret)
        @session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
        name: @advert.book.title,
        description: "by #{@advert.book.authors}",
        images: [@advert.book.image_link],
        amount: (@advert.price * 100).to_i,
        currency: 'aud',
        quantity: 1,
}],
success_url: order_complete_url,
cancel_url: order_cancel_url,
)
    end

    def complete
    end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/adverts/index.html.erb
<h1 class="title">Book Store</h1>
<p class="subtitle">Select a Book to Purchase</p>

<table class="table is-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Condition</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <% if @adverts %>
            <% @adverts.each do |advert| %>
                <tr>
                    <td><%= link_to advert.book.title, advert_path(advert.id)%></td>
                    <td><%= advert.condition %></td>
                    <td><%= number_to_currency advert.price %></td>
                </tr>
            <%end%>
        <%end%> 
    </tbody>
</table>

<p><%= link_to("Back", exchange_index_path, :class => "button")%></p>

app/views/adverts/new.html.erb
<div class="columns">
    <div class="column is-three-fifths">
        <h1 class="title">Create an Ad</h1>
        <h1 class="subtitle"><%= @current_book.title %></h1>
        <div class="column">
            <%= image_tag(@current_book.image_link, :class => "image") %>
        </div>    
        <div class="column">
            <h3>Author: <%= @current_book.authors %></h3>
            <h3>ISBN: <%= @current_book.isbn %></h3>
        </div>
        <br>
        <%= form_with model: @advert, local:true do |f| %>
        <%= f.hidden_field :book_id, :value => @current_book.id %>
        <%= f.hidden_field :seller_id, :value => current_user.id %>
        <div class="field">
            <%=label(:price, 'Price', :class => 'label')%>
            <div class="control">
                <%= f.number_field :price, required: true, step: :any, :class => 'input', :type => 'number'%>
            </div>
        </div>
        <div class="field">
            <%=label(:condition, 'Condition', :class => 'label')%>
            <div class="control">
                <%= f.select :condition, ['Brand New', 'Like New', 'Very Good', 'Good', 'Acceptable']%>
            </div>
        </div>
        <div class="field">
            <%=label(:cover, 'Add an image', :class => 'label')%>
            <div class="control">
                <%= f.file_field :cover%>
            </div>
        </div>
        <p><%= f.submit "Post", :class => 'button is-primary' %></p><br>
        <p><%= link_to("Back", books_path, :method => :get , :class => 'button') %></p>
        <%end%>
    </div>
</div>

app/views/adverts/show.html.erb
<div class="columns">
    <div class="column is-three-fifths">
        <h1 class="title"><%= @advert.book.title %></h1>
        <h2 class="subtitle"><%= @advert.book.authors %></h2>
        <% if @advert.cover == true %>
            <%= image_tag(@advert.cover, width: 200) %>
        <% else %>
            <%= image_tag(@advert.book.image_link, :class => "image") %>
        <% end %>
        <br>
            <p class="subtitle">Description</p>
            <p><%= @advert.book.description %></p>
        <br>
            <h2>Condition: <%= @advert.condition %></h2>
            <h2>Contact: <%= @advert.seller.email%></h2>
            <h2>Price: <%=number_to_currency @advert.price %></h2>
        <br>
        <% if @advert.seller_id != current_user.id %>
            <p><%= link_to("Order", new_order_path(advert_id: @advert.id), :class => "button is-primary") %></p><br>       
        <%end%>        
        <% if @advert.seller_id == current_user.id %>
            <p><%= link_to "Delete", @advert, method: :delete, :class => "button is-primary" %></p>
            <br>
        <%end%>
        <p><%= link_to("Back", adverts_path, :class => 'button') %></p>
    </div>
</div>

app/views/books/index.html.erb
<h1 class="title">Book List</h1>
<p class="subtitle">Select or Add a Book to Sell</p>

<table class="table is-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author(s)</th>
            <th>ISBN</th>
        </tr>
    </thead>
    <tbody>
        <% if @books %>
            <% @books.each do |i| %>
                <tr>
                    <td><%= link_to i.title, book_path(i.id) %></td>
                    <td><%= i.authors %></td>
                    <td><%= i.isbn %></td>
                </tr>
            <%end%>
        <%end%>
    </tbody>
</table>

<p><%= link_to("Add", new_book_path, :class => "button is-primary")%></p><br>
<p><%= link_to("Back", exchange_index_path, :class => "button")%></p>

app/views/books/new.html.erb
<h1 class="title">Add a Book to Sell</h1>
<div class="columns">
    <div class="column is-two-fifths">
        <%= form_with model: @book, local:true do |form| %>
            <div class="field">
                <%=label(:title, 'Title', :class => 'label')%>
                <div class="control">
                    <%= form.text_field :title, required: true, minlength: 1, :class => 'input', :type => 'text'%>
                </div>
            </div>
            <p><%= form.submit "Add", :class => 'button is-primary' %></p><br>
            <p><%= link_to("Back", books_path, :method => :get, :class => 'button') %></p>
        <%end%>
    </div>
</div>

app/views/books/show.html.erb
<div class="columns">
    <div class="column is-three-fifths">
        <h1 class="title"><%= @book.title %></h1>
        <h2 class="subtitle"><%= @book.authors %></h2>
        <%= image_tag(@book.image_link, :class => "image") %>
        <br>
        <p class="subtitle">Description:<p>
        <p><%= @book.description %></p>
        <br>
        <p><%= link_to("Sell", new_advert_path(book_id: @book.id), :class => "button is-primary") %></p><br>
        <p><%= link_to("Back", books_path, :class => 'button') %></p>
    </div>
</div>

app/views/exchange/about.html.erb
<div class="columns">
    <div class="column is-two-fifths">
        <h1 class="title">About</h1>
        
        <p>
        As students and avid readers, the creators of <strong>Bookly</strong> have amassed quite a collection of books. As they looked around one day, they noticed their bookshelves overflowing with wonderful books of all kinds. Books they had once enjoyed but now, sadly, sat gathering dust. They were sure others too would have amazing collections of books to share. All those fantastic books deserved to find a new home where their words would be read and enjoyed again.
        <br>And so, <strong>Bookly</strong> came to be <em>your one stop shop for book exchange</em>! Please sign up, browse, buy, enjoy and sell.
        <br>From the team at <strong>Bookly</strong> ... Happy Reading!
        </p>
        <br>
        <%= image_tag("startup-594091_640.jpg", :class => "imgCard")%>
        <br>
        <footer>
            <p><small>&copy; Copyright Jack Gronow, Tony Huynh & Natalie Sargent 2019</small></p>
        </footer>
    </div>
</div>

app/views/exchange/contact.html.erb
<h1 class="title">Contact</h1>
<div class="columns">
    <div class="column is-two-fifths">
        <form action="https://usebasin.com/f/31e19b13edf3" method="POST">
            <div class="field">
                <label for="name" class="label">Name</label>
                <div class="control">
                <input type="text" id="name" name="name" placeholder="Your name..." class="input">
                </div>
            </div>
            <div class="field">
                <label for="email" class="label">Email</label>
                <div class="control">
                    <input type="text" id="email" name="email" placeholder="Your email address..." class="input">
                </div>
            </div>
            <div class="field">
                <label for="message" class="label">Message</label>
                <div class="control">
                    <textarea id="message" name="message" placeholder="Write something..." class="textarea"></textarea>
                </div>
            </div>
                <input class="button is-link" type="submit" value="Submit">
        </form>
        <br><p><%= link_to("Back", exchange_index_path, :class => "button")%></p>
    </div>
</div>

app/views/exchange/index.html.erb
<h1 class="title is-size-1">Bookly</h1>
<p class="subtitle">Your one stop shop for <span class="highlight">book exchange</span></p>
<%= image_tag("books-389392_640.jpg", :class => "imgCard")%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <head>
      <%= render "shared/topnav" %>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <p class="flash"><%= flash[:info] %></p>
      </div>
    </head>
    <div class="container section">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/complete.html.erb
<h1 class="title">Thank you <%= current_user.firstname.capitalize %></h1>
<br>
<h3 class="subtitle">Your order was successful.</h3>

<p><%= link_to("Continue Shopping", adverts_path, :class => "button is-primary")%></p>

app/views/orders/new.html.erb
<h1 class="title">View Your Order</h1>

<table class="table is-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Author</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
                  <tr>
                    <td><%= @advert.book.title%></td>
                    <td><%= @advert.book.authors%></td>
                    <td><%= number_to_currency @advert.price %></td>
                </tr>
    </tbody>
</table>
<p><%= link_to("Checkout", new_order_path(advert_id: @advert.id), :class => "button is-primary") %></p><br>

<script src="https://js.stripe.com/v3/"></script>

<script>
    var stripe = Stripe('pk_test_ZHuJyiYgWYeKRpyIwMTnqAFe00fP2ZKjHg');
    stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
    }).then(function (result) {
    // If `redirectToCheckout` fails due to a browser or network
    // error, display the localized error message to your customer
    // using `result.error.message`.
    });
    </script>

<p><%= link_to("Back", adverts_path, :class => "button")%></p>

app/views/shared/_topnav.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a>
        <%= link_to image_tag('logo.png'), exchange_index_path, :class => "navbar-item" %>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a>
          <%= link_to "Home", exchange_index_path, :class => "navbar-item"%>
        </a>

        <a>
          <%= link_to "Buy", adverts_path, :class => "navbar-item"%>
        </a>

        <a>
          <%= link_to "Sell", books_path, :class => "navbar-item"%>
        </a>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>

          <div class="navbar-dropdown">
            <a>
              <%= link_to "About", about_path, :class => "navbar-item" %>
            </a>
            <a>
              <%= link_to "Documentation", "https://github.com/sizsan/Bookly", :class => "navbar-item" %>
            </a>
            <hr class="navbar-divider">
            <a>
              <%= link_to "Contact", contact_path, :class => "navbar-item" %>
            </a>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
              <a>
                  <% if user_signed_in? %>
                    <div id="username" class="button is-dark"><%= current_user.firstname.capitalize %></div>
                    <div id="logout"><%= link_to 'Logout', destroy_user_session_path, method:
                    "delete",class:"button is-light"%></div>
                  <% else %>
                    <p><%= link_to 'Sign Up', new_user_registration_path, class:"button is-primary"%>
                    <%= link_to 'Login', new_user_session_path, class:"button is-light"%>
                    </p>
                  <% end %>
              </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>